### PR TITLE
allow passing $(DESTDIR)

### PR DESCRIPTION
**Pull request by HRio**

### CODE REVIEW

**Comment by HRio** [comment]
@bahamas10 did you see this change?

REF: https://git.alpinelinux.org/cgit/aports/tree/testing/zfs-prune-snapshots/APKBUILD

**Comment by bahamas10** [comment]
thank you! and thank you for the bump.  sorry i've been a bit busy recently but i do appreciate these!

**Comment by bahamas10** [comment]
`v1.0.1` pushed with this change.

**Comment by HRio** [comment]
@bahamas10 thanks! 1.0.1 is now in alpine https://git.alpinelinux.org/cgit/aports/commit/?id=bab7a8c4902b77d1146141b526723a555b79c172

**Pull request merged**
